[app_proxy]
vm-app-proxy

[master]
10.0.1.20

[master:vars]
ansible_user="{{ lookup('env', 'VM_USER') | default('azureuser', true) }}"
ansible_password="{{ lookup('env', 'VM_PASSWORD') }}"
ansible_become_password="{{ lookup('env', 'VM_PASSWORD') }}"
ansible_host_key_checking=False

ansible_ssh_common_args="-o ProxyCommand=\"sshpass -p '{{ lookup('env', 'VM_PASSWORD') }}' ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 {{ lookup('env', 'VM_USER') }}@{{ lookup('env', 'VM1_PUBLIC_IP') }}\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
