---
app_runtime_container_name: "ecommerce-app"
app_runtime_image_name: "ecommerce-app:latest"
app_runtime_host_port: 80
app_runtime_container_port: 3000

# Gunakan IP privat VM1 agar container app mencapai port ProxySQL yang diekspos di host.
app_runtime_db_host: "10.0.1.10"
app_runtime_db_port: "6033"
app_runtime_db_user: "app_user"
app_runtime_db_password: "{{ lookup('env', 'DB_APP_PASSWORD') }}"
app_runtime_db_name: "ecommerce"
